# Programação Python para Ciência de Dados

## Exercícios Numpy e Pandas - Parte I

### Prática dos conteúdos estudados: Processando e extraindo informações de arquivos csv

In [10]:
import numpy as np
import pandas as pd

#### O arquivo 'WorldCups.csv' possui as colunas:
- Year: ano da copa
- Country: pais sede
- Winner: campeão
- RunnersUP: disputou a final com o campeão
- Third: terceiro colocado
- Fourth: quarto colocado
- GoalsScored: número de gols na copa
- QualifiedTeams:
- MatchesPlayed: número de jogos
- Attendance: número de espectadores

#### 1) Leia o arquivo 'WorldCups.csv', definindo a coluna 'Year' como índice, e salve-o em uma variável. Exiba as 5 primeiras linhas e o tipo de dado de cada coluna. Quantas linhas possui o DataFrame?

In [11]:
df = pd.read_csv('WorldCups.csv',index_col = 'Year')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20 entries, 1930 to 2014
Data columns (total 9 columns):
Country           20 non-null object
Winner            20 non-null object
RunnersUp         20 non-null object
Third             20 non-null object
Fourth            20 non-null object
GoalsScored       20 non-null int64
QualifiedTeams    20 non-null int64
MatchesPlayed     20 non-null int64
Attendance        20 non-null object
dtypes: int64(3), object(6)
memory usage: 1.6+ KB


In [13]:
df.head()

Country      Winner       RunnersUp    Third      Fourth  \
Year                                                                 
1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia   
1934        Italy       Italy  Czechoslovakia  Germany     Austria   
1938       France       Italy         Hungary   Brazil      Sweden   
1950       Brazil     Uruguay          Brazil   Sweden       Spain   
1954  Switzerland  Germany FR         Hungary  Austria     Uruguay   

      GoalsScored  QualifiedTeams  MatchesPlayed Attendance  
Year                                                         
1930           70              13             18    590.549  
1934           70              16             17    363.000  
1938           84              15             18    375.700  
1950           88              13             22  1.045.246  
1954          140              16             26    768.607

In [14]:
len(df)

20

In [16]:
df.dtypes

Country           object
Winner            object
RunnersUp         object
Third             object
Fourth            object
GoalsScored        int64
QualifiedTeams     int64
MatchesPlayed      int64
Attendance        object
dtype: object

#### 2) Em quais anos o Brasil ganhou a copa? Em quais anos o Brasil jogou uma final? Qual a proporção de vitórias do Brasil em finais?

In [17]:
# Em quais anos o Barsil ganhou a copa:
df[df['Winner']=='Brazil'].index.values

array([1958, 1962, 1970, 1994, 2002])

In [18]:
df.loc[df['Winner'] == 'Brazil'].index.values

array([1958, 1962, 1970, 1994, 2002])

In [19]:
 df[ (df['Winner'] == 'Brazil') | (df['RunnersUp'] == 'Brazil') ].index.values

array([1950, 1958, 1962, 1970, 1994, 1998, 2002])

In [20]:
# Brasil jogou uma final: Winner or RunnersUp
df.query("Winner == 'Brazil' or RunnersUp  == 'Brazil'").index.values

array([1950, 1958, 1962, 1970, 1994, 1998, 2002])

#### 3) Remova as colunas de QualifiedTeams e 'MatchesPlayed'

In [21]:
df.drop(['QualifiedTeams', 'MatchesPlayed'] ,axis = 1,inplace = True)
df.columns

Index(['Country', 'Winner', 'RunnersUp', 'Third', 'Fourth', 'GoalsScored',
       'Attendance'],
      dtype='object')

#### 4) Exiba as linhas de 4 a 8 (inclusive)

In [22]:
df.iloc[4:9,:]

Country      Winner       RunnersUp       Third        Fourth  \
Year                                                                      
1954  Switzerland  Germany FR         Hungary     Austria       Uruguay   
1958       Sweden      Brazil          Sweden      France    Germany FR   
1962        Chile      Brazil  Czechoslovakia       Chile    Yugoslavia   
1966      England     England      Germany FR    Portugal  Soviet Union   
1970       Mexico      Brazil           Italy  Germany FR       Uruguay   

      GoalsScored Attendance  
Year                          
1954          140    768.607  
1958          126    819.810  
1962           89    893.172  
1966           89  1.563.135  
1970           95  1.603.975

#### 5) Utiliza os rótulos (labels) para exibir as linhas das copas de 2002 e 2006 

In [23]:
df.loc[[2002,2006]]

Country  Winner RunnersUp    Third          Fourth  GoalsScored  \
Year                                                                        
2002  Korea/Japan  Brazil   Germany   Turkey  Korea Republic          161   
2006      Germany   Italy    France  Germany        Portugal          147   

     Attendance  
Year             
2002  2.705.197  
2006  3.359.439

#### 6) Quais foram as 5 copas com mais gols? Utilize a função de ordenação.

In [24]:
df.sort_values('GoalsScored').iloc[-5:]

Country   Winner   RunnersUp        Third          Fourth  \
Year                                                                  
1982        Spain    Italy  Germany FR       Poland          France   
2006      Germany    Italy      France      Germany        Portugal   
2002  Korea/Japan   Brazil     Germany       Turkey  Korea Republic   
1998       France   France      Brazil      Croatia     Netherlands   
2014       Brazil  Germany   Argentina  Netherlands          Brazil   

      GoalsScored Attendance  
Year                          
1982          146  2.109.723  
2006          147  3.359.439  
2002          161  2.705.197  
1998          171  2.785.100  
2014          171  3.386.810

In [25]:
df.sort_values('GoalsScored').tail()

Country   Winner   RunnersUp        Third          Fourth  \
Year                                                                  
1982        Spain    Italy  Germany FR       Poland          France   
2006      Germany    Italy      France      Germany        Portugal   
2002  Korea/Japan   Brazil     Germany       Turkey  Korea Republic   
1998       France   France      Brazil      Croatia     Netherlands   
2014       Brazil  Germany   Argentina  Netherlands          Brazil   

      GoalsScored Attendance  
Year                          
1982          146  2.109.723  
2006          147  3.359.439  
2002          161  2.705.197  
1998          171  2.785.100  
2014          171  3.386.810

#### 7) Utiliza o método `.value_counts()` para saber o número de vezes que cada país já ganhou. Só é necessário usar a coluna 'Winner' 

In [26]:
df['Winner'].value_counts()

Brazil        5
Italy         4
Germany FR    3
Argentina     2
Uruguay       2
Spain         1
England       1
Germany       1
France        1
Name: Winner, dtype: int64

#### 8) Deixe Pandas de lado por enquanto. Vamos para o Numpy.
Os dados de pandas são na verdade uma matriz do Numpy. Trabalhar com a matriz Numpy é mais eficiente. Para acessar essa matriz basta fazer:

```python
nparray = dataframe.values
```

##### a) Com a matriz numpy, visualize apenas as colunas de 1 a 4 (inclusive). Que colunas são essas? Salve numa variável.

In [27]:
matriz = df.values[:,1:5]
matriz

array([['Uruguay', 'Argentina', 'USA', 'Yugoslavia'],
       ['Italy', 'Czechoslovakia', 'Germany', 'Austria'],
       ['Italy', 'Hungary', 'Brazil', 'Sweden'],
       ['Uruguay', 'Brazil', 'Sweden', 'Spain'],
       ['Germany FR', 'Hungary', 'Austria', 'Uruguay'],
       ['Brazil', 'Sweden', 'France', 'Germany FR'],
       ['Brazil', 'Czechoslovakia', 'Chile', 'Yugoslavia'],
       ['England', 'Germany FR', 'Portugal', 'Soviet Union'],
       ['Brazil', 'Italy', 'Germany FR', 'Uruguay'],
       ['Germany FR', 'Netherlands', 'Poland', 'Brazil'],
       ['Argentina', 'Netherlands', 'Brazil', 'Italy'],
       ['Italy', 'Germany FR', 'Poland', 'France'],
       ['Argentina', 'Germany FR', 'France', 'Belgium'],
       ['Germany FR', 'Argentina', 'Italy', 'England'],
       ['Brazil', 'Italy', 'Sweden', 'Bulgaria'],
       ['France', 'Brazil', 'Croatia', 'Netherlands'],
       ['Brazil', 'Germany', 'Turkey', 'Korea Republic'],
       ['Italy', 'France', 'Germany', 'Portugal'],
       ['Spai

##### b) Você deve gerar um dicionário em que as chaves são os países e os valores são número de vezes que aquele país participou de uma final (Ex.: 'pais' : num_final).

_Dica: o código abaixo pode te auxiliar a criar esse dicionário_

```python
# d é um dicionário que inicialmente estava vazio
if pais in d: 
    d[pais] += 1 # se país estava no dicionário...
else:
    d[pais] = 1 # # se país não estava no dicionário...
```

In [28]:
dic = {}
for primeiro, segundo, _, _ in matriz:
    
    if primeiro not in dic:
        dic[primeiro] = 1
        
    else:
        dic[primeiro] += 1
        
    if segundo not in dic:
        dic[segundo] = 1
        
    else:
        dic[segundo] += 1

dic

{'Uruguay': 2,
 'Argentina': 5,
 'Italy': 6,
 'Czechoslovakia': 2,
 'Hungary': 2,
 'Brazil': 7,
 'Germany FR': 6,
 'Sweden': 1,
 'England': 1,
 'Netherlands': 3,
 'France': 2,
 'Germany': 2,
 'Spain': 1}

##### b) Agora faça um dicionário que mapeia cada país ao número de partidas que disputou terceiro lugar (Ex.: 'pais' : num_terc).

In [29]:
dic2={}
for _, _, terceiro, quarto in matriz:
    
    if terceiro not in dic2:
        dic2[terceiro] = 1
    else:
        dic2[terceiro] += 1
    
    if quarto not in dic2:
        dic2[quarto] = 1
    else:
        dic2[quarto] += 1
    
dic

{'Uruguay': 2,
 'Argentina': 5,
 'Italy': 6,
 'Czechoslovakia': 2,
 'Hungary': 2,
 'Brazil': 7,
 'Germany FR': 6,
 'Sweden': 1,
 'England': 1,
 'Netherlands': 3,
 'France': 2,
 'Germany': 2,
 'Spain': 1}

##### c) Insira esses dois dicionários em em outro dicionário da seguinte forma {'finais' : {'Brazil' : 7, ...}, 'tercs' : {USA' : 1}}. Transforme em um DataFrame e salve em um arquivo .csv.

In [30]:
dic3 = {'finais':dic,'terceiros':dic2}

In [41]:
dic3

{'finais': {'Uruguay': 2,
  'Argentina': 5,
  'Italy': 6,
  'Czechoslovakia': 2,
  'Hungary': 2,
  'Brazil': 7,
  'Germany FR': 6,
  'Sweden': 1,
  'England': 1,
  'Netherlands': 3,
  'France': 2,
  'Germany': 2,
  'Spain': 1},
 'terceiros': {'USA': 1,
  'Yugoslavia': 2,
  'Germany': 3,
  'Austria': 2,
  'Brazil': 4,
  'Sweden': 3,
  'Spain': 1,
  'Uruguay': 3,
  'France': 3,
  'Germany FR': 2,
  'Chile': 1,
  'Portugal': 2,
  'Soviet Union': 1,
  'Poland': 2,
  'Italy': 2,
  'Belgium': 1,
  'England': 1,
  'Bulgaria': 1,
  'Croatia': 1,
  'Netherlands': 2,
  'Turkey': 1,
  'Korea Republic': 1}}

In [42]:
df_final = pd.DataFrame(dic3)

In [34]:
df_final

finais  terceiros
Argentina          5.0        NaN
Austria            NaN        2.0
Belgium            NaN        1.0
Brazil             7.0        4.0
Bulgaria           NaN        1.0
Chile              NaN        1.0
Croatia            NaN        1.0
Czechoslovakia     2.0        NaN
England            1.0        1.0
France             2.0        3.0
Germany            2.0        3.0
Germany FR         6.0        2.0
Hungary            2.0        NaN
Italy              6.0        2.0
Korea Republic     NaN        1.0
Netherlands        3.0        2.0
Poland             NaN        2.0
Portugal           NaN        2.0
Soviet Union       NaN        1.0
Spain              1.0        1.0
Sweden             1.0        3.0
Turkey             NaN        1.0
USA                NaN        1.0
Uruguay            2.0        3.0
Yugoslavia         NaN        2.0

In [44]:
df_final.to_csv('df_final_lab_modulo3')